import type { Metadata } from "next"

import { AppProvider } from "@/providers/app"

import "../styles/globals.css"
import { baiJamjuree } from "@/styles/fonts"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${baiJamjuree.className}  antialiased`}>
                <AppProvider>{children}</AppProvider>
            </body>
        </html>
    )
}
