import type { Metadata } from "next"

import { baiJamjuree } from "@/styles/fonts"
import { AppProvider } from "@/providers/app"

import { AppHeader } from "@/components/layouts"
import { Toaster } from "@/components/ui/sonner"

import "../styles/globals.css"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${baiJamjuree.className}  antialiased`}>
                <AppProvider>
                    <div className="w-100 h-100 px-24">
                        <AppHeader />
                        {children}
                    </div>
                    <Toaster />
                </AppProvider>
            </body>
        </html>
    )
}
